# -*- coding: utf-8 -*-
"""Heuristica-Codig 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oRwyA1opgGTzlIoYgr-Q4z46ZQDCzpK9
"""

import random

def exibir_tabuleiro(tabuleiro):
    print("-------------")
    for i in range(3):
        print("|", end=" ")
        for j in range(3):
            print(tabuleiro[i][j], end=" | ")
        print("\n-------------")

def verificar_vitoria(tabuleiro, jogador):
    for i in range(3):
        if tabuleiro[i][0] == tabuleiro[i][1] == tabuleiro[i][2] == jogador:
            return True

    for i in range(3):
        if tabuleiro[0][i] == tabuleiro[1][i] == tabuleiro[2][i] == jogador:
            return True

    if tabuleiro[0][0] == tabuleiro[1][1] == tabuleiro[2][2] == jogador:
        return True
    if tabuleiro[0][2] == tabuleiro[1][1] == tabuleiro[2][0] == jogador:
        return True

    return False

def verificar_empate(tabuleiro):
    return ' ' not in [celula for linha in tabuleiro for celula in linha]

def fazer_jogada(tabuleiro, jogador):
    while True:
        linha = int(input("Digite o número da linha (0-2): "))
        coluna = int(input("Digite o número da coluna (0-2): "))

        if linha < 0 or linha > 2 or coluna < 0 or coluna > 2:
            print("Jogada inválida! Tente novamente.")
            continue

        if tabuleiro[linha][coluna] != ' ':
            print("Posição ocupada! Tente novamente.")
            continue

        tabuleiro[linha][coluna] = jogador
        break

def fazer_jogada_ia_heuristica(tabuleiro, jogador):
    for i in range(3):
        for j in range(3):
            if tabuleiro[i][j] == ' ':
                tabuleiro[i][j] = jogador
                if verificar_vitoria(tabuleiro, jogador):
                    return
                tabuleiro[i][j] = ' '

    jogador_humano = 'O' if jogador == 'X' else 'X'
    for i in range(3):
        for j in range(3):
            if tabuleiro[i][j] == ' ':
                tabuleiro[i][j] = jogador_humano
                if verificar_vitoria(tabuleiro, jogador_humano):
                    tabuleiro[i][j] = jogador
                    return
                tabuleiro[i][j] = ' '

    fazer_jogada_ia_aleatoria(tabuleiro, jogador)

def fazer_jogada_ia_aleatoria(tabuleiro, jogador):
    while True:
        linha = random.randint(0, 2)
        coluna = random.randint(0, 2)

        if tabuleiro[linha][coluna] == ' ':
            tabuleiro[linha][coluna] = jogador
            break

def jogar_jogo_da_velha():
    tabuleiro = [[' ' for _ in range(3)] for _ in range(3)]
    jogadores = ['X', 'O']
    jogador_atual = random.choice(jogadores)

    while True:
        exibir_tabuleiro(tabuleiro)
        print("Jogador atual:", jogador_atual)

        if jogador_atual == 'X':
            fazer_jogada(tabuleiro, jogador_atual)
        else:
            fazer_jogada_ia_heuristica(tabuleiro, jogador_atual)

        if verificar_vitoria(tabuleiro, jogador_atual):
            exibir_tabuleiro(tabuleiro)
            print("O jogador", jogador_atual, "venceu!")
            break
        elif verificar_empate(tabuleiro):
            exibir_tabuleiro(tabuleiro)
            print("O jogo terminou em empate!")
            break

        jogador_atual = 'O' if jogador_atual == 'X' else 'X'

jogar_jogo_da_velha()